apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: command
  name: command
spec:
  containers:
  - image: busybox:latest
    name: command
    command: ["ping"]
    args: ["-c","60","google.com"]