apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: rakshith
  name: rakshith
spec:
  containers:
  - image: nginx
    name: rakshith
    resources: {}
    env: 
    - name: CHILL_MACCHA
      valueFrom:
        secretKeyRef:
          name: rakshith
          key: env
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
