apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: rakshith
  name: rakshith-demo
spec:
  volumes:
  - name: secret-volume
    secret:
      secretName: rakshith     
  containers:
  - image: nginx
    name: rakshith
    resources: {}
    volumeMounts:
    - name: secret-volume
      mountPath: /var/lib
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
