apiVersion: v1
kind: PersistentVolume
metadata:
  name: rakshith-volume
spec:
  storageClassName: local-path # this sc is based on killerkoda 
  capacity:
    storage: "1Gi"
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /var/lib