apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: rakshith
  name: hostpath-pod
spec:
  volumes:
  - name: pvc-volume
    persistentVolumeClaim:
      claimName: rakshith-pvc
  containers:
  - image: nginx
    name: rakshith
    resources: {}
    volumeMounts:
    - name: pvc-volume
      mountPath: /var/lib
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}