apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: rakshith
  name: hostpath-pod
spec:
  volumes:
  - name: hostpath-volume
    hostPath:
      path: /data  
      type: DirectoryOrCreate 
  containers:
  - image: nginx
    name: rakshith
    resources: {}
    volumeMounts:
    - name: hostpath-volume
      mountPath: /var/lib
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}